Default: &defaults
  user: episodes
  password: episodes
  host: localhost
  port: 5432
  database: episodes
  poolsize: 10

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  poolsize: 100
  <<: *defaults

Production:
  poolsize: 100
  <<: *defaults
