Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Maciej Pietrzak
  #analytics: UA-YOURCODE

Development:
  <<: *defaults
  update-interval: 3600
  update-count: 4

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://3.pisod.es"
  <<: *defaults
  update-interval: 36000
  update-count: 128
