Default: &defaults
  database: episodes.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: episodes_test.sqlite3
  <<: *defaults

Staging:
  database: episodes_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: episodes_production.sqlite3
  poolsize: 100
  <<: *defaults
